---
title: "Summary of Refinitiv vs. BBG"
author: "Siddharth Engineer"
date: "6/30/2021"
output: pdf_document
---

Intel 5-year:
```{r}
library(readxl)
data <- read_excel("C:/Users/ME/OneDrive/Desktop/Raw data/BBG-Eikon Comparison.xlsx")


ref = data$`Intel 5Y Eikon`
bbg = data$`Intel 5Y BBG`
bbg = as.numeric(bbg)

plot(ref, bbg)

unfiltered = ref - bbg
filtered = c()
count = 0
for(x in unfiltered){
  if(!is.na(x)){
    filtered[count] = x
    count = count + 1
  }
}

plot(filtered, type="l")
abline(h=0)

mean(filtered)
sd(filtered)
t.test(filtered, alternative = "two.sided", mu=0, conf.level=0.95)

cor(ref, bbg, use="complete.obs")
```

Nike 5-year
```{r}
library(readxl)
data <- read_excel("C:/Users/ME/OneDrive/Desktop/Raw data/BBG-Eikon Comparison.xlsx")


ref = data$`Nike 5Y Eikon`
bbg = data$`Nike 5Y BBG`
bbg = as.numeric(bbg)

plot(ref, bbg)

unfiltered = ref - bbg
filtered = c()
count = 0
for(x in unfiltered){
  if(!is.na(x)){
    filtered[count] = x
    count = count + 1
  }
}

plot(filtered, type="l")
abline(h=0)

mean(filtered)
sd(filtered)
t.test(filtered, alternative = "two.sided", mu=0, conf.level=0.95)

cor(ref, bbg, use="complete.obs")
```

Comcast 5-year
```{r}
library(readxl)
data <- read_excel("C:/Users/ME/OneDrive/Desktop/Raw data/BBG-Eikon Comparison.xlsx")


ref = data$`Comcast 5Y Eikon`
bbg = data$`Comcast 5Y BBG`
bbg = as.numeric(bbg)

plot(ref, bbg)

unfiltered = ref - bbg
filtered = c()
count = 0
for(x in unfiltered){
  if(!is.na(x)){
    filtered[count] = x
    count = count + 1
  }
}

plot(filtered, type="l")
abline(h=0)

mean(filtered)
sd(filtered)
t.test(filtered, alternative = "two.sided", mu=0, conf.level=0.95)

cor(ref, bbg, use="complete.obs")
```

Intel 30-year
```{r}
library(readxl)
data <- read_excel("C:/Users/ME/OneDrive/Desktop/Raw data/BBG-Eikon Comparison.xlsx")


ref = data$`Intel 30Y Eikon`
bbg = data$`Intel 30Y BBG`
bbg = as.numeric(bbg)

plot(ref, bbg)

unfiltered = ref - bbg
filtered = c()
count = 0
for(x in unfiltered){
  if(!is.na(x)){
    filtered[count] = x
    count = count + 1
  }
}

plot(filtered, type="l")
abline(h=0)

mean(filtered)
sd(filtered)
t.test(filtered, alternative = "two.sided", mu=0, conf.level=0.95)

cor(ref, bbg, use="complete.obs")
```

Nike 30-year
```{r}
library(readxl)
data <- read_excel("C:/Users/ME/OneDrive/Desktop/Raw data/BBG-Eikon Comparison.xlsx")


ref = data$`Nike 30Y Eikon`
bbg = data$`Nike 30Y BBG`
bbg = as.numeric(bbg)

plot(ref, bbg)

unfiltered = ref - bbg
filtered = c()
count = 0
for(x in unfiltered){
  if(!is.na(x)){
    filtered[count] = x
    count = count + 1
  }
}

plot(filtered, type="l")
abline(h=0)

mean(filtered)
sd(filtered)
t.test(filtered, alternative = "two.sided", mu=0, conf.level=0.95)

cor(ref, bbg, use="complete.obs")
```

Comcast 30-year
```{r}
library(readxl)
data <- read_excel("C:/Users/ME/OneDrive/Desktop/Raw data/BBG-Eikon Comparison.xlsx")


ref = data$`Comcast 30Y Eikon`
bbg = data$`Comcast 30Y BBG`
bbg = as.numeric(bbg)

plot(ref, bbg)

unfiltered = ref - bbg
filtered = c()
count = 0
for(x in unfiltered){
  if(!is.na(x)){
    filtered[count] = x
    count = count + 1
  }
}

plot(filtered, type="l")
abline(h=0)

mean(filtered)
sd(filtered)
t.test(filtered, alternative = "two.sided", mu=0, conf.level=0.95)

cor(ref, bbg, use="complete.obs")
```